#!/usr/bin/env bash

pushd /usr/local/var/genenews
git checkout .
git pull git://github.com/christandiono/genenews.git
rm -rf /usr/local/var/genenews/settings_local.py
ln -s /usr/local/var/genenews/settings_local.production /usr/local/var/genenews/settings_local.py
python manage.py syncdb
python manage.py evolve --hint --execute
/etc/rc.d/uwsgi stop
/etc/rc.d/uwsgi start
popd
